// <auto-generated />
using CitiesManager.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CitiesManager.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230806165116_CityNameRequired")]
    partial class CityNameRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.WebApi.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("3377b955-7aad-46a1-8e42-a4564fd1c664"),
                            CityName = "Jerusalem"
                        },
                        new
                        {
                            CityID = new Guid("dd2a0f96-f9e9-40ec-9719-4d88d4bc1a23"),
                            CityName = "Athens"
                        },
                        new
                        {
                            CityID = new Guid("d4d68d61-2e25-40ee-9d62-49a71586248d"),
                            CityName = "Rome"
                        },
                        new
                        {
                            CityID = new Guid("bc9e17c6-a6cf-47a3-9c16-6cdfed114723"),
                            CityName = "Beirut"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
